global:
  resolve_timeout: 5m 
route:
  group_by:
  - cluster
  - alertname
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  routes:
  - receiver: slack-notifications
    match:
      alertname: warning
receivers:
- name: slack-notifications
  slack_configs:
  - channel: "#geral"
    api_url: 'https://hooks.slack.com/services/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'
    send_resolved: true
    title: "[Alert] {{ .GroupLabels.alertname }}"
    text: "summary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"
